### ISSUE TITLE
google_mobile_ads:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by sernocturno** [googleads/googleads-mobile-flutter#855]
i have a problem after update flutter to 3.0.2
here is the fragment with error

> [  +14 ms] > Task :webview_flutter_android:generateDebugBuildConfig UP-TO-DATE
> [  +39 ms] > Task :webview_flutter_android:javaPreCompileDebug UP-TO-DATE
> [  +19 ms] > Task :webview_flutter_android:compileDebugJavaWithJavac UP-TO-DATE
> [ +108 ms] > Task :webview_flutter_android:bundleLibCompileToJarDebug UP-TO-DATE
> [+1774 ms] > Task :google_mobile_ads:compileDebugJavaWithJavac
> [   +7 ms] C:\Users\turco\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_mobile_ads-3.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterMobileAdsWrapper.java:79: error: static interface method
> invocations are not supported in -source 7
> [  +13 ms]     WebView webView = WebViewFlutterAndroidExternalApi.getWebView(flutterEngine, webViewId);
> [   +4 ms]                                                       ^
> [  +15 ms]   (use -source 8 or higher to enable static interface method invocations)
> [        ] Note: Some input files use or override a deprecated API.
> [  +49 ms] Note: Recompile with -Xlint:deprecation for details.
> [  +31 ms] 1 error
> [   +2 ms] > Task :google_mobile_ads:compileDebugJavaWithJavac FAILED
> [  +79 ms] FAILURE: Build failed with an exception.
> [   +2 ms] * What went wrong:
> [   +7 ms] Execution failed for task ':google_mobile_ads:compileDebugJavaWithJavac'.
> [   +3 ms] > Compilation failed; see the compiler error output for details.
> [   +1 ms] * Try:
> [   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> [   +1 ms] * Get more help at https://help.gradle.org
> [  +14 ms] BUILD FAILED in 18s
> [   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> [        ] Use '--warning-mode all' to show the individual deprecation warnings.
> [  +14 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
> [  +28 ms] 136 actionable tasks: 5 executed, 131 up-to-date
> [ +642 ms] Running Gradle task 'assembleDebug'... (completed in 19.8s)
> [   +6 ms] Exception: Gradle task assembleDebug failed with exit code 1
> [   +4 ms] "flutter run" took 21,913ms.
> [   +8 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
>            <asynchronous suspension>
>            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
>            <asynchronous suspension>
>            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
>            <asynchronous suspension>
>            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
>            <asynchronous suspension>
>            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
>            <asynchronous suspension>
>            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
>            <asynchronous suspension>
>            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #10     main (package:flutter_tools/executable.dart:94:3)
>            <asynchronous suspension>
> 
> 
> [ +203 ms] ensureAnalyticsSent: 193ms
> [   +1 ms] Running shutdown hooks
> [        ] Shutdown hooks complete
> [        ] exiting with code 1

i dont know what this line means

> error: static interface method invocations are not supported in -source 7
    WebView webView = WebViewFlutterAndroidExternalApi.getWebView(flutterEngine, webViewId);
                                                      ^
  (use -source 8 or higher to enable static interface method invocations)

if somebody can help with this issue

**Comment by huycozy** [comment]
Hi @sernocturno 
It seems the issue is caused by Gradle version, please check [this](https://github.com/googleads/googleads-mobile-flutter/issues/831#issuecomment-1534407228) and also try the same way to solve the issue.

Closing as a duplicate issue. If you still experience the issue after trying that solution, please write in the comments and I will reopen this for further investigation. Thank you!
