### ISSUE TITLE
Can't compile with native ads

### ISSUE THREAD

**Issue by erperejildo** [googleads/googleads-mobile-flutter#450]
`google_mobile_ads: ^1.0.0`

I took this example and ran it ok: https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example

To implement it on my project I followed these steps: https://developers.google.com/admob/flutter/native

First thing I tried was build Google's example with my pubspec.yaml and both build.gradles to check nothing were getting in conflict and it worked.

So I moved then to my project and copied these 3 files:
- MainActivity.java
- NativeAdFactoryExample.java
- my_native_ad.xml

When I build the app I don't get any error in the console but it stops working:
<img width="263" alt="Screenshot 2021-11-28 at 11 03 58" src="https://user-images.githubusercontent.com/5629919/143765197-5e562034-4211-4fbe-b844-d66b2dbc3cb6.png">

Flutter doctor:

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [✓] Xcode - develop for iOS and macOS
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.62.0)
    [✓] Connected device (3 available)
    
    • No issues found!

P.S: I was already showing banners, interstitial and rewards ads in my app.

**Comment by erperejildo** [comment]
Actually I do get errors, but they are shown as normal logs, not like errors (I didn't see it):
```
FATAL EXCEPTION: main
E/AndroidRuntime(16282): Process: com.drodriguez.my_rents, PID: 16282
E/AndroidRuntime(16282): java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: WorkManager is already initialized.  Did you try to initialize it manually without disabling WorkManagerInitializer? See WorkManager#initialize(Context, Configuration) or the class level Javadoc for more information.
E/AndroidRuntime(16282): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
```

If I add this fix that I found:
```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            tools:node="remove" />
...
implementation "androidx.startup:startup-runtime:1.0.0"
```

I get this other error (and this now is a proper error):
```
* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'buildConfigPackageName'.
   > Failed to query the value of property 'packageName'.
      > org.xml.sax.SAXParseException; systemId: file:/Users/dani/repos/dani/my_rents/android/app/src/main/AndroidManifest.xml; lineNumber: 71; columnNumber: 35; The prefix "tools" for attribute "tools:node" associated with an element type "provider" is not bound.
```

**Comment by maheshmnj** [comment]
Hi @erperejildo, looking at the error logs they don't seem related to the ads plugin but related to Android or specifically to AndroidX.

**Comment by erperejildo** [comment]
hmm ok. Thing is that I go this after updating the package from 0.13 to 1.
I'll try to do similar update for a new project to see if I get this working or if I get different errors.

**Comment by erperejildo** [comment]
Ok @maheshmnj , I could reproduce similar problem (after updating, not exactly the error I got). 
So cloned this project: https://github.com/SnippetCoders/flutter_admob. Both this project and mine support Kotlin.

- It works fine with 0.13
- Updated `targetSdkVersion` and `compileSdkVersion` to 31. Still working fine
- Updated `google_mobile_ads` fom 0.13 to 1 and now got this issue:
```
e: /Users/dani/.gradle/caches/transforms-2/files-2.1/683fded33b117c0eb9bb9deabca1a71e/work-runtime-2.7.0-api.jar!/META-INF/work-runtime_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by erperejildo** [comment]
Ok, found a fix for this. Probably is worth to document this to support Kotlin projects as well.

About my original error there should be some conflict with one of my versions/packages but at least this is working with a fresh copy.
