### ISSUE TITLE
[📚] NativeAd - Kotlin & Swift documentation

### ISSUE THREAD

**Issue by QuentinSc** [googleads/googleads-mobile-flutter#45]
Hello,

For non native developpers like me, it could be essential to have kotlin code version of the native code which is used to create native ads.

Thank you !

**Comment by MaximeDelhorme** [comment]
That would be very nice because I'm trying to implement it in Kotlin using this code:

```
import android.graphics.Color
import android.view.LayoutInflater
import android.widget.TextView
import com.google.android.gms.ads.formats.UnifiedNativeAd
import com.google.android.gms.ads.formats.UnifiedNativeAdView
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.NativeAdFactory
import java.util.Map;

internal class NativeAdFactoryExample(layoutInflater: LayoutInflater) : NativeAdFactory {
    private val layoutInflater: LayoutInflater

    @Override
    fun createNativeAd(
            nativeAd: UnifiedNativeAd, customOptions: Map<String, Object>): UnifiedNativeAdView {
        val adView: UnifiedNativeAdView = layoutInflater.inflate(R.layout.my_native_ad, null) as UnifiedNativeAdView
        val headlineView: TextView = adView.findViewById(R.id.ad_headline)
        val bodyView: TextView = adView.findViewById(R.id.ad_body)
        headlineView.setText(nativeAd.getHeadline())
        bodyView.setText(nativeAd.getBody())
        adView.setBackgroundColor(Color.YELLOW)
        adView.setNativeAd(nativeAd)
        adView.setBodyView(bodyView)
        adView.setHeadlineView(headlineView)
        return adView
    }

    init {
        this.layoutInflater = layoutInflater
    }
}
```

But I keep running in the following error:
NativeAdFactoryExample.kt: (11, 10): Class 'NativeAdFactoryExample' is not abstract and does not implement abstract member public abstract fun createNativeAd(p0: UnifiedNativeAd!, p1: (Mutable)Map<String!, Any!>!): UnifiedNativeAdView! defined in io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.NativeAdFactory

And I don't know how to solve it. 
If someone can help in the meanwhile, that would be nice.

Thanks!

**Comment by MaximeDelhorme** [comment]
I got it to compile with Kotlin:

Here is the code I used for NativeAdFactoryExample.kt:

`
import android.graphics.Color
import android.view.LayoutInflater
import android.widget.TextView
import com.google.android.gms.ads.formats.UnifiedNativeAd
import com.google.android.gms.ads.formats.UnifiedNativeAdView
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.NativeAdFactory
import java.util.Map;

class NativeAdFactoryExample(layoutInflater: LayoutInflater) : NativeAdFactory {
    private val layoutInflater: LayoutInflater

    override fun createNativeAd(
            nativeAd: UnifiedNativeAd, customOptions: MutableMap<String, Any>): UnifiedNativeAdView {
        val adView: UnifiedNativeAdView = layoutInflater.inflate(R.layout.my_native_ad, null) as UnifiedNativeAdView
        val headlineView: TextView = adView.findViewById(R.id.ad_headline)
        val bodyView: TextView = adView.findViewById(R.id.ad_body)
        headlineView.setText(nativeAd.getHeadline())
        bodyView.setText(nativeAd.getBody())
        adView.setBackgroundColor(Color.YELLOW)
        adView.setNativeAd(nativeAd)
        adView.setBodyView(bodyView)
        adView.setHeadlineView(headlineView)
        return adView
    }

    init {
        this.layoutInflater = layoutInflater
    }
}
`

**Comment by QuentinSc** [comment]
Thank you @MaximeDelhorme, I will give it a try today

**Comment by QuentinSc** [comment]
Arg @MaximeDelhorme, got the same error 
`e: C:\src\gamevent_getx\android\app\src\main\kotlin\com\quentinsc\gamevent_getx\NativeAdFactoryExample.kt: (30, 66): Unresolved reference: R
e: C:\src\gamevent_getx\android\app\src\main\kotlin\com\quentinsc\gamevent_getx\NativeAdFactoryExample.kt: (31, 58): Unresolved reference: R
e: C:\src\gamevent_getx\android\app\src\main\kotlin\com\quentinsc\gamevent_getx\NativeAdFactoryExample.kt: (32, 54): Unresolved reference: R
`

**Comment by MaximeDelhorme** [comment]
@QuentinSc Did you include the package name at the top of your file?

package com.name.name

**Comment by QuentinSc** [comment]
> @QuentinSc Did you include the package name at the top of your file?
> 
> package com.name.name

Haha I had check twice... and now I see a typo..
So my bad, compilation is working now! Thank you

**Comment by edex96** [comment]
Here is the full code to make the Native ad work without crash in kotlin


**MainActivity.kt**
```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.NativeAdFactory


class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        val factory: NativeAdFactory = NativeAdFactoryExample(layoutInflater)
        GoogleMobileAdsPlugin.registerNativeAdFactory(flutterEngine, "adFactoryExample", factory)
    }

    override fun cleanUpFlutterEngine(flutterEngine: FlutterEngine) {
        GoogleMobileAdsPlugin.unregisterNativeAdFactory(flutterEngine, "adFactoryExample")
    }
}
```


**NativeAdFactoryExample.kt**
```
import android.graphics.Color
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.widget.TextView
import com.google.android.gms.ads.formats.UnifiedNativeAd
import com.google.android.gms.ads.formats.UnifiedNativeAdView
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.NativeAdFactory


internal class NativeAdFactoryExample(private val layoutInflater: LayoutInflater) : NativeAdFactory {
    override fun createNativeAd(
        nativeAd: UnifiedNativeAd, customOptions: Map<String, Any>?): UnifiedNativeAdView {
        val adView = layoutInflater.inflate(R.layout.my_native_ad, null) as UnifiedNativeAdView
        val headlineView = adView.findViewById<TextView>(R.id.ad_headline)
        val bodyView = adView.findViewById<TextView>(R.id.ad_body)
        headlineView.text = nativeAd.headline
        bodyView.text = nativeAd.body
        adView.setBackgroundColor(Color.YELLOW)
        adView.setNativeAd(nativeAd)
        adView.bodyView = bodyView
        adView.headlineView = headlineView
        return adView
    }
}
```

**Comment by kunny** [comment]
I recently updated the [Adding an AdMob banner and native inline ads to a Flutter app](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7) codelab to cover writing a native ad factory in Kotlin and Swift. You can find a [Sample code](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/tree/main/complete_kotlin_swift) as well :)

**Comment by Vakil-Parth** [comment]
i am having issue

`Class 'ListTileNativeAdFactory' is not abstract and does not implement abstract member public abstract fun createNativeAd`

**Comment by nero-angela** [comment]
> I recently updated the [Adding an AdMob banner and native inline ads to a Flutter app](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7) codelab to cover writing a native ad factory in Kotlin and Swift. You can find a [Sample code](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/tree/main/complete_kotlin_swift) as well :)

This codelab only works with `google_mobile_ads: ^0.12.0`. Needs a fix to make it work with ^0.13.0 version.

**Comment by kunny** [comment]
Hey everyone - please to share that the updated [the codelab](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter) which is compatible with the latest plugin (0.13.0) is now available. 

Please check it out and leave and let me know if you have any issues. Thanks!
