### ISSUE TITLE
The latest version 0.13.0 can not build on Mac m1 xCode Ver 12.3

### ISSUE THREAD

**Issue by aoboinfo** [googleads/googleads-mobile-flutter#256]
There is no problem for Android.
But iOS can not finish successfully.

**Comment by suesitran** [comment]
same problem, here's my build log

Launching lib/main.dart on <device> in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ************
Running pod install...
Running Xcode build...
Xcode build done.                                           38.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Google-Mobile-Ads-SDK-gdiovfcfrmjigzcegpmcnukjrxbk
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_ListTileNativeAdFactory", referenced from:
          objc-class-ref in AppDelegate.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Google-Mobile-Ads-SDK-gdiovfcfrmjigzcegpmcnukjrxbk
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/FirebaseCore/FirebaseCore.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/gRPC-C++/grpcpp.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/gRPC-Core/grpc.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/GTMAppAuth/GTMAppAuth.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/FirebaseAuth/FirebaseAuth.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/FirebaseInstallations/FirebaseInstallations.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/FirebaseFirestore/FirebaseFirestore.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/url_launcher/url_launcher.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/primary_secondary_progress_bar/primary_secondary_progress_bar.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/sqflite/sqflite.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/path_provider/path_provider.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/BoringSSL-GRPC/openssl_grpc.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/qr_code_scanner/qr_code_scanner.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/FMDB/FMDB.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/google_sign_in/google_sign_in.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/gRPC-C++/gRPCCertificates-Cpp.bundle'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/google_mobile_ads/google_mobile_ads.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/firebase_core/firebase_core.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/firebase_auth/firebase_auth.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/package_info/package_info.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/firebase_analytics/firebase_analytics.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/nanopb/nanopb.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/Runner.app'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/cloud_firestore/cloud_firestore.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/device_info/device_info.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/Pods_Runner.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/abseil/absl.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/apple_sign_in/apple_sign_in.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/MTBBarcodeScanner/MTBBarcodeScanner.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/leveldb-library/leveldb.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/GoogleUtilities/GoogleUtilities.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/GoogleDataTransport/GoogleDataTransport.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/GTMSessionFetcher/GTMSessionFetcher.framework'

    note: Removed stale file '/Users/456545/Library/Developer/Xcode/DerivedData/Runner-fislrjpqyjipbrefdeaskmrhldgo/Build/Products/Debug-iphoneos/AppAuth/AppAuth.framework'


Could not build the precompiled application for the device.

Error launching application on <device>.

**Comment by EArminjon** [comment]
I've mac M1. I can help you if you provide some logs.

**Comment by aoboinfo** [comment]
Thank you very much.
I return to the old version 0.12.2 which can used without any problem.
