### ISSUE TITLE
Failed to build iOS  Error (Xcode): Undefined symbol: _SKStoreProductParameterAdNetworkSourceIdentifier

### ISSUE THREAD

**Issue by hicnar** [googleads/googleads-mobile-flutter#827]
The version 3.0.0 of the plugin will not build on iOS.
Xcode v 13.2.1 (13C100) on Big Sur

**Comment by huycozy** [comment]
Hi @hicnar, can you please provide the complete output of `flutter run -v` so that we may verify it?

**Comment by hicnar** [comment]
Here you are
[runv.log.zip](https://github.com/googleads/googleads-mobile-flutter/files/11327427/runv.log.zip)
PS. Android works just fine

**Comment by huycozy** [comment]
Thanks for providing the log. But I can not reproduce this issue from my end on iOS device (iPhone 7, iOS 15.7.2). 

What is your current device (OS, model)? Can you please check if the issue can reproduce with [plugin example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)?

**Comment by hicnar** [comment]
I try to run it on iOS simulator that comes with Xcode (version above) all running on macOS Big Sur version 11.4. You may try exactly this config since there were problems with another flutter package (flutter_purchases) and they were caused by a change that was not backwards compatible with Big Sur which were later fixed. Not saying that this is the same but looks very similar. Will try to run the plugin example later today.

**Comment by huycozy** [comment]
Unfortunately, I don't have macOS Big Sur and the same XCode version. I'm on macOS Ventura 13.0.1, Xcode 14.3. The ads load fine on iPhone 14 Pro, iOS 16.04 emulator. 

Can you please provide the output of `flutter doctor -v`? And please also try running and confirm if the crash also occurs with [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example).

**Comment by BitBlueDevStudio** [comment]
Same error!
New version = new bugs?

**Comment by hicnar** [comment]
@huycozy 
Below is a zipped log captured when I attempted to run the packages/google_mobile_ads/example/lib/main.dart
[run-v-example-main.log.zip](https://github.com/googleads/googleads-mobile-flutter/files/11391367/run-v-example-main.log.zip)
Same result

**Comment by huycozy** [comment]
@hicnar Thanks, it's helpful. Can you please provide the output of `flutter doctor -v` as well?

**Comment by hicnar** [comment]
[✓] Flutter (Channel stable, 3.7.12, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at /Users/khycnar/Development/flutter_2.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/khycnar/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/khycnar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8770.15

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 78964DE1-4450-47A1-B601-1F38C49B9FF3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 113.0.5672.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by hicnar** [comment]
I have two projects both using googleads-mobile-flutter tried both, neither works with the most recent version, the example project does not work either, another guy pointed out he's having the same problem. What else can I do? It is not the architecture, it is something with the library introduced in the last release.

**Comment by huycozy** [comment]
Thanks for your response. Labeling the issue for further insights from the team.

<details>
<summary>Error log extracted from the complete log above</summary>

```console
           Undefined symbols for architecture x86_64:
             "_SKStoreProductParameterAdNetworkSourceIdentifier", referenced from:
                 l030 in GoogleMobileAds(GADInAppStoreMonitor.o)
           ld: symbol(s) not found for architecture x86_64
           clang: error: linker command failed with exit code 1 (use -v to see invocation)


           Result bundle written to path:
            /var/folders/47/xy_zycl96zd4s9rrxds3j6hr0000gn/T/flutter_tools.bXuKRM/flutter_ios_build_temp_dir9wCVRB/temporary_xcresult_bundle


           ** BUILD FAILED **


           The following build commands failed:
            Ld /Users/khycnar/IdeaProjects/googleads-mobile-flutter2/packages/google_mobile_ads/example/build/ios/Debug-iphonesimulator/Runner.app/Runner normal (in target 'Runner' from project 'Runner')
           (1 failure)
[   +7 ms]  └─Compiling, linking and signing... (completed in 601ms)
[        ] Xcode build done.  
```
</details>


cc: @jjliu15

**Comment by zumatrahia** [comment]
I also have same problem

**Comment by zumatrahia** [comment]
I have made some research and maybe I can help the team for problem solving. My machine have Monterey version 12.1 which supports up to Xcode 13.3.1 which supports iOS 15.4.
SKStoreProductParameterAdNetworkSourceIdentifier is needed for SKAdNetwork 4 which works on iOS 16.1 or later. 
In my understanding flutter tries to give a value to SKStoreProductParameterAdNetworkSourceIdentifier but cant find any and gives a build time error.
If it possible if you can make it work for iOS versions below 16.1 by bypassing value initialization to SKStoreProductParameterAdNetworkSourceIdentifier it would work but it is just my guess

**Comment by HosseinArabbeigi** [comment]
Same issue here.

**Comment by carpentierchloe** [comment]
Same issue

**Comment by huycozy** [comment]
For anyone else facing this issue, please do not leave "me too" or "same here" comments on this thread. Please give a thumb-up reaction on the top-level comment that will help the team to prioritize the issue. Thanks!

**Comment by pdmshrestha** [comment]
Seems like the issue is with older xcode version. I am using macOS Big Sur 11.7.7
`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.10.1, on macOS 11.7.7 20G1345 darwin-x64, locale en-FI)
    • Flutter version 3.10.1 on channel stable at /Users/pdm/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (2 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/pdm/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)            
    • iPhone 13 Pro Max (mobile) • 432B4314-D1FC-4AE7-A134-2017BE38FC77 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.7.7 20G1345 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.
```

**Comment by jjliu15** [comment]
GMA iOS version 10.4.0 increased the minimum supported xcode version to 14.1: https://developers.google.com/admob/ios/rel-notes, so this is intended. Will update the changelog

**Comment by timothyhoang-google** [comment]
@jjliu15 - I'll leave this open until the changelog is updated.

**Comment by malandr2** [comment]
Closing this out as the changelog has been updated.
